// Trang tạm: hiển thị JSON kết quả từ /ai-advisor/generate-skill-tree.
// Khi có shape response thật, thay khối <pre> bằng component vẽ cây kỹ năng.
export default function SkillTreePage() {
  return (
    <div className='flex-1 min-h-0 overflow-y-auto p-6'>
      <div className='max-w-5xl mx-auto'>
        <h1 className='text-[28px] font-bold text-gray-900'>Skill Tree</h1>
        <p className='mt-1 text-gray-500 text-[15px]'>Your skills, gaps and next steps, generated by the AI mentor.</p>
      </div>
    </div>
  )
}
